---
- name: Install ntp server on controller node
  apt:
    name: chrony
    state: present
  tags:
    - ntp

- name: Configuring chrony
  template: src=chrony.j2  dest=/etc/chrony/chrony.conf
  notify:
   - restart chrony
  changed_when: true
  tags:
    - ntp

