---
- name: restart gnocchi-api
  service: 
    name: gnocchi-api
    state: restarted

- name: restart gnocchi-metricd
  service:
    name: gnocchi-metricd
    state: restarted

- name: restart ceilometer-agent-central
  service: 
    name: ceilometer-agent-central
    state: restarted
- name: restart ceilometer-agent-notification 
  service:
    name: ceilometer-agent-notification
    state: restarted 
