---


- name: Install rabbitmq server
  apt: name=rabbitmq-server state=latest force=yes
  notify: restart rabbitmq
  tags:
     - rabbitmq

- name: Add rabbitmq user
  rabbitmq_user: user={{ rabbit_userid }}
                 password={{ rabbit_pass }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  tags:
     - rabbitmq
