---

- name: Config the external net interface
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ external }}
      iface {{ external }} inet manual
      up ip link set dev $IFACE up
      down ip link set dev $IFACE down
  tags:
     - neutron

- name: Insert controller sysconf
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.ip_forward = 1
      net.ipv4.conf.all.rp_filter = 0
      net.ipv4.conf.default.rp_filter = 0 
  tags:
     - neutron
   
- name: update sysctl
  shell: sysctl -p
  tags:
     - neutron

- name: Create neutron database
  mysql_db: 
    name: "{{ neutron_db_name }}"
    state: present
  tags:
     - neutron

- name: Create neutron user in database
  mysql_user: 
    name: "{{ neutron_db_user }}"
    password: "{{ neutron_db_pass }}"
    host: "{{ item }}"
    priv: '*.*:ALL,GRANT'
    state: present
  with_items:
      - "localhost"
      - "%"
  tags:
     - neutron

- name: Create the neutron user
  os_user: 
    name: "{{ neutron_db_user }}"
    password: "{{ neutron_db_pass }}"
    domain: default
    state: present
  environment: "{{ admin_env }}"
  tags:
     - neutron

- name: Add the admin role to the neutron user
  os_user_role: 
    user: neutron
    role: admin
    project: service
    state: present
  environment: "{{ admin_env }}"
  tags:
     - neutron

- name: Create the neutron service entity
  os_keystone_service:
    state: present
    name: neutron
    service_type: network
    description: OpenStack Networking
  environment: "{{ admin_env }}"
  tags:
     - neutron

- name: Create the Networking service API endpoints
  shell: openstack endpoint create --region RegionOne network {{ item }} http://{{ neutron_hostname }}:9696 
  with_items:
      - public
      - internal
      - admin
  environment: "{{ admin_env }}"
  tags:
     - neutron

- name: Install neutron controller packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items: 
   - neutron-server 
   - neutron-plugin-ml2 
   - neutron-openvswitch-agent
   - neutron-l3-agent
   - neutron-dhcp-agent
   - neutron-metadata-agent
   - python-neutronclient 
  tags:
     - neutron

- name: Configure neutron
  template: 
    src: neutron.j2
    dest: /etc/neutron/neutron.conf
  notify:
   - restart neutron-server
  changed_when: true
  tags:
     - neutron


- name: Configure neutron-l3-agent
  template: 
    src: l3_agent.j2 
    dest: /etc/neutron/l3_agent.ini
  notify: restart neutron-l3-agent
  changed_when: true
  tags:
     - neutron

- name: Configure neutron-dhcp-agent
  template: 
    src: dhcp_agent.j2
    dest: /etc/neutron/dhcp_agent.ini
  notify: restart neutron-dhcp-agent
  changed_when: true
  tags:
     - neutron

- name: Configure neutron-dnsmasq
  template: 
    src: dnsmasq-neutron.j2 
    dest: /etc/neutron/dnsmasq-neutron.conf
  tags:
     - neutron

- name: Configure neutron-metadata-agent
  template: 
    src: metadata_agent.j2 
    dest: /etc/neutron/metadata_agent.ini
  notify: restart neutron-metadata-agent
  tags:
     - neutron

- name: Configure neutron-plugin-ml2
  template: 
    src: ml2_conf.j2 
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  tags:
     - neutron

- name: Configure openvswitch_agent
  template:
    src: openvswitch_agent.j2 
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
  notify: 
     - restart openvswitch-switch
     - restart neutron-openvswitch-agent
  changed_when: true
  tags:
     - neutron


- name: Sync neutron database
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf  --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  tags:
     - neutron

- meta: flush_handlers
  tags:
     - neutron


- name: Add br-ex
  openvswitch_bridge: 
    bridge: br-ex 
    state: present
  tags:
     - neutron

- name: Add port to br-ex
  openvswitch_port: 
    bridge: br-ex
    port: "{{ external }}"
    state: present
  tags:
     - neutron

