---
- name: Install NTP Server On Computer Nodes and Other Nodes
  apt:
    name: chrony
    state: present
  tags:
    - ntp-compute

- name: Configuring chrony
  template: src=chrony.j2  dest=/etc/chrony/chrony.conf
  notify:
   - restart chrony
  changed_when: true
  tags:
    - ntp-compute

